Update superdove and flower notebooks to use ref ids
sedaro/modsim-notebooks pull request #13
Opened 2023-07-18 17:36 UTC by zduvall

Update supderdove with ref ids

2023-07-18 17:40 UTC, ryanporzeinski285 approved these changes

2023-07-25 14:00 UTC, baswelsh requested changes
Thanks Zach - could we also update the Flowers NB?

2023-07-26 15:54 UTC, baswelsh approved these changes

2023-07-31 18:45 UTC, baswelsh approved these changes

2023-07-31 18:45 UTC, merged