Add routines notebook
sedaro/modsim-notebooks pull request #26
Opened 2024-01-31 16:33 UTC by starskin

This adds the `routines.ipynb` notebook, which explains the different kinds of `Routine` and gives examples for creating each type.

2024-02-20 22:58 UTC, rtumin2 requested changes
Looks good!  I think some small adjustments to the code are needed, and some rewording in the guidance could be helpful.

2024-02-20 22:58 UTC, rtumin2 commented on examples/routines.ipynb
> +    "Before Sedaro 4.9, the internal logic of agents was mostly driven by operational modes. These had important capabilities, like being able to prioritize certain operational modes above others or
```suggestion
    "Before Sedaro 4.9, the internal logic of agents was mostly driven by operational modes. These provided significant utility, but they also had limitations, such as the inability to have two operational modes active simultaneously or to drive the selection of the active operational mode with logic other than conditions and priority. Since the release of 4.9, the functionality of `OperationalMode` has been replaced by `Routine`, which allows for much more comprehensive, complicated, and customizable behavior for agents in Sedaro. Routines are similar to operational modes in that they are used to drive important behavioral logic like active modes and interfaces, but they come in different types that each have their own functionality.\n",
```

2024-02-20 22:58 UTC, rtumin2 commented on examples/routines.ipynb
> +    "- [`CombinationalLogic`](#combinationallogic-routines): A specialized `Routine` block that is associated with various prioritized `LogicalConfiguration` options\n",
```suggestion
    "- [`CombinationalLogic`](#combinationallogic-routines): A specialized `Routine` block that is associated with various prioritized `LogicalConfiguration` options and re-creates the functionality of operational modes.\n",
```

2024-02-20 22:58 UTC, rtumin2 commented on examples/routines.ipynb
> +    "- A set of associated routines with a common ancestor (which itself does not have any parent routines) is called a `Routine` \"program\".\n",
```suggestion
    "- A set of associated routines with a common ancestor (which itself does not have any parent routines) is called a \"program\".\n",
```

2024-02-20 22:58 UTC, rtumin2 commented on examples/routines.ipynb
> +    "- As long as they are not in the same `Routine` program, more than one `Routine` can be active at a time.\n",
```suggestion
    "- Otherwise, more than one `Routine` can be active at a time.\n",
```
It's notable that many subroutines in the same program will be active

2024-02-20 22:58 UTC, rtumin2 commented on examples/routines.ipynb
> +    "- Since only one pointing mode can be active at a time, only one `Routine` program can control the agent's active pointing mode.\n"
Not sure if this fits here but I leave it up to your discretion

2024-02-20 22:58 UTC, rtumin2 commented on examples/routines.ipynb
> +    "A `CombinationalLogic` routine is associated with a set of `LogicalConfiguration` blocks, each of which is assigned a priority, conditions that must be met for the `LogicalConfiguration` to be a
```suggestion
    "Each subroutine of a `CombinationalLogic` is associated with a `LogicalConfiguration` block. Each `LogicalConfiguration` can be defined by a list of conditions, priority, a minimum occurrence duration, maximum occurrence duration, and a minimum time between occurrences. The active subroutine is the one whose `LogicalConfiguration` has the highest `priority` and is compliant. This is equivalent to the behavior of Operational Modes except that any subroutine may optionally be designated as the default subroutine, becoming active when no associated `LogicalConfiguration`s are compliant. \n",
```

2024-02-20 22:58 UTC, rtumin2 commented on examples/routines.ipynb
> +    "combinational_logic = agent_template.CombinationalLogic.create(\n",
I can test this tomorrow, but I would be surprised if this doesn't throw a Tier2Error, since `subroutines` is required.

2024-02-20 22:58 UTC, rtumin2 commented on examples/routines.ipynb
> +    "        example_routine_1.id: {'activeTimes': [({'s': 1}, {'min': 1}), ({'hour': 1}, {'min': 70})]},\n",
I know you want to show off quantity kinds, but I think switching between during each interval just makes the example more confusing.

2024-02-20 22:58 UTC, rtumin2 commented on examples/routines.ipynb
> +    "    transitions=[transition_1.id, transition_2.id],\n",
Once again, I suspect you will need to define `subroutines`.

2024-02-29 15:34 UTC, starskin commented on examples/routines.ipynb
> +    "    transitions=[transition_1.id, transition_2.id],\n",
Will this still be the case with the coming update?

2024-02-29 18:52 UTC, starskin commented on examples/routines.ipynb
> +    "combinational_logic = agent_template.CombinationalLogic.create(\n",
Defining the `subroutines` field directly will not be required in the newest update

2024-02-29 18:54 UTC, rtumin2 commented on examples/routines.ipynb
> +    "- Since only one pointing mode can be active at a time, only one `Routine` program can control the agent's active pointing mode.\n"
Maybe it would fit better if you said something like "Some behaviors are controlled by the combination of active `Routine`s within a single program. For example, since only one pointing mode..."  I'm fine with whatever you think is best

2024-02-29 18:56 UTC, rtumin2 approved these changes

2024-03-04 19:12 UTC, merged