Revisit & Comms Analytics Notebook
sedaro/modsim-notebooks pull request #46
Opened 2024-12-13 19:20 UTC by starskin

2024-12-17 03:05 UTC, baswelsh commented
Thanks @starskin!  Could you add this to the table of contents too?

2024-12-28 05:31 UTC, rtumin2 requested changes
I still need to create a test scenario to test out the plots. In general, there are some changes needed to make the notebook more accessible (in my opinion)

2024-12-28 05:31 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "- `REVISIT_ANALYSIS_CONDITION`: The name of the condition that is met when an observer agent revisits a target agent. There must be a `TargetGroupCondition` with this name on each of the observe
This is probably prohibitively complicated for a user to set up if they're slightly interested. Could you pre-populate these IDs with a sample scenario? Or at least leave the plots in the notebook so the user can see the benefit of setting all of this up? An advertisement if you will

2024-12-28 05:31 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "DATA_ANALYSIS_DATA_TYPES: list[str] = []\n",
Maybe make this into two variables instead of four by checking for `''` or `[]`

2024-12-28 05:31 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "results = scenario.simulation.results() if not JOB_ID else scenario.simulation.results(JOB_ID)\n",
```suggestion
    "results = scenario.simulation.results(JOB_ID)\n",
```
this can handle the job id being `None`

2024-12-28 05:31 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "## Analysis Functions"
From previous discussions with Bas, I think we want these sorts of functions to be imported from a utils file instead of defined in the notebook. It makes using the client and the notebook more intimidating

2024-12-28 05:31 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "        display(bar)\n",
Does this need to be toggleable?

2024-12-28 05:31 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "            for compliance, group in groupby(enumerate(compliance_series), key=lambda x: x[1]):\n",
It is worth adding comments in this function, especially this groupby

2024-12-28 05:31 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "def target_data_results(\n",
Once again, comments are needed here to help any users who want to edit this code to do a similar analysis

2024-12-28 05:31 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "## Perform Analysis"
This should be one cell to make it easier to run

2024-12-28 05:31 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "# Results"
No need to have extra cells for this, resolution ideas below

2024-12-28 05:31 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +  {
If you want this to be user configurable, just have them set this directly at the top with something like
```py
px.defaults.template = "plotly_dark" # "plotly_white"
```

2024-12-28 05:31 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "def scale_data_units(value: float, bytes: bool = False) -> tuple[float, str]:\n",
to utils

2024-12-31 19:52 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "- `REVISIT_ANALYSIS_CONDITION`: The name of the condition that is met when an observer agent revisits a target agent. There must be a `TargetGroupCondition` with this name on each of the observe
What is the reasoning for using the name here? I used the id instead of the name because I wasn't expecting it to use the name

2024-12-31 21:21 UTC, rtumin2 commented
@starskin I'll ask you to clean this up (e.g. by giving a better name to the map I made), but this change is needed to handle targets that exist as standalone targets and as a member of the target group. In this case, the agent id and target id are not the same.

https://github.com/sedaro/modsim-notebooks/pull/46/commits/51e4364230d5a72f848169a854202139cf3c8256

2024-12-31 21:26 UTC, rtumin2 commented
I tested the revisit plots with this scenario and the plots look good!  However I made a condition that is true only when multiple targets are available (count>0) and used that as the revisit condition. I'm not sure how to interpret this plot whenever two targets are involved. Maybe we should add a disclaimer that the results are really for conditions that use "ANY".  Perhaps you have some insight into this?


<img width="1153" alt="image" src="https://github.com/user-attachments/assets/14c875b9-da0d-4cc7-af72-9b3044540ae7" />

Also, here's the scenario I'm using to test
[thanos-UnitedAirlinesAirTrafficControlScenariosimport.zip](https://github.com/user-attachments/files/18283717/thanos-UnitedAirlinesAirTrafficControlScenariosimport.zip)

2025-01-01 01:32 UTC, rtumin2 commented
I used this nb with TDRSS demo, and the data results say there is no transmit or receive data. However, web indicates that there was tx and rx.

<img width="641" alt="image" src="https://github.com/user-attachments/assets/72941e56-aedc-4168-938f-c8db51428ef1" />

https://sedarocorp-my.sharepoint.us/:u:/g/personal/richard_tuminello_sedaro_com/EdLkZtDhDf9CqAEO4U4z16UB695istju8yjgMeUlcuoNfg?e=b57uLb

2025-01-02 16:36 UTC, starskin commented on examples/revisit_and_comm_analytics.ipynb
> +    "!pip install \"sedaro>=4.16.2\""
That's a good point I hadn't considered. I'll change it now.

2025-01-02 19:28 UTC, starskin commented on examples/revisit_and_comm_analytics.ipynb
> +    "HOST = config['HOST']  # Sedaro instance URL"
I'm inclined to agree that specifying the `HOST` is unnecessary for most users, but getting it from the `config.json` file is something we do in most—if not all—of our notebooks. Do you think I should just remove it here and have the `SedaroApiClient` object use the default `host`?

2025-01-02 19:29 UTC, starskin commented on examples/revisit_and_comm_analytics.ipynb
> +    "HOST = config['HOST']  # Sedaro instance URL"
Also if I instantiate the client in this cell I would have to move the Analysis Configuration section to be above this cell. Does that seem alright to you?

2025-01-02 19:44 UTC, starskin commented on examples/revisit_and_comm_analytics.ipynb
> +    "- `REVISIT_ANALYSIS_CONDITION`: The name of the condition that is met when an observer agent revisits a target agent. There must be a `TargetGroupCondition` with this name on each of the observe
I believe the notebook should work out-of-the-box with the Wildfire scenario. I'll try to set it up so that it has these values by default and the plots are there as well.

2025-01-02 19:48 UTC, starskin commented on examples/revisit_and_comm_analytics.ipynb
> +    "- `REVISIT_ANALYSIS_CONDITION`: The name of the condition that is met when an observer agent revisits a target agent. There must be a `TargetGroupCondition` with this name on each of the observe
My reasoning was that if you use a name, you can have different agent templates with different conditions that have the same name so they could both be used for the revisit condition.

2025-01-02 19:52 UTC, starskin commented
> @starskin I'll ask you to clean this up (e.g. by giving a better name to the map I made), but this change is needed to handle targets that exist as standalone targets and as a member of the target group. In this case, the agent id and target id are not the same.
> 
> [51e4364](https://github.com/sedaro/modsim-notebooks/commit/51e4364230d5a72f848169a854202139cf3c8256)
@rtumin2 
I had originally tried to do something like this but the format of the revisit condition results is different between the two cases, so I decided to only use agent & target groups for the revisit condition. If a condition for a target is used instead of a target group, the following line in target_revisit_results breaks:
```python
for target_id, compliance_series in compliance_values.items():
```
Do you think it's a high priority to support both individual agents/targets in addition to agent/target groups?

2025-01-02 19:55 UTC, starskin commented on examples/revisit_and_comm_analytics.ipynb
> +    "def scale_data_units(value: float, bytes: bool = False) -> tuple[float, str]:\n",
I'll format this function better and make an MR for it to be included in [the `sedaro` utils](https://github.com/sedaro/sedaro-python/blob/main/sedaro/src/sedaro/utils.py).

2025-01-02 19:59 UTC, starskin commented on examples/revisit_and_comm_analytics.ipynb
> +    "def scale_data_units(value: float, bytes: bool = False) -> tuple[float, str]:\n",
Or do you think it should go in [`sedaro.modsim`](https://github.com/sedaro/sedaro-python/blob/main/sedaro/src/sedaro/modsim.py)?

2025-01-02 21:42 UTC, starskin commented on examples/revisit_and_comm_analytics.ipynb
> +  {
Do you think the Analysis Configuration cell is the best place for this?

2025-01-02 22:00 UTC, starskin commented on examples/revisit_and_comm_analytics.ipynb
> +    "        display(bar)\n",
Probably not, no. I'll make it always on and that should simplify some of the code.

2025-01-02 22:09 UTC, starskin commented on examples/revisit_and_comm_analytics.ipynb
> +    "DATA_ANALYSIS_DATA_TYPES: list[str] = []\n",
For `REVISIT_ANALYSIS` and `REVISIT_ANALYSIS_CONDITION` this makes sense since if `REVISIT_ANALYSIS` is `True` then `REVISIT_ANALYSIS_CONDITION` would have to have a value anyway. For `DATA_ANALYSIS` however, the user could leave `DATA_ANALYSIS_DATA_TYPES` empty and it would consider all data types if `DATA_ANALYSIS` is `True`. We can consolidate both variables if we are okay with requiring the user to manually specify the names of all of the data types they would like the notebook to consider.

2025-01-02 22:42 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "HOST = config['HOST']  # Sedaro instance URL"
Fair point about the config, feel free to do whatever you prefer. 

re: instantiating the client. I don't see why you'd need to move anything above this; you could just put `sedaro = SedaroApiClient(API_KEY, HOST)` here

2025-01-02 22:44 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "def scale_data_units(value: float, bytes: bool = False) -> tuple[float, str]:\n",
Sorry for being unclear; you can just make a sibling file `utils.py` and put this in there.

2025-01-02 22:44 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "- `REVISIT_ANALYSIS_CONDITION`: The name of the condition that is met when an observer agent revisits a target agent. There must be a `TargetGroupCondition` with this name on each of the observe
Ok, I'd at least make it consistent with configuring the data type, which requires an ID currently, right?

2025-01-02 22:46 UTC, starskin commented on examples/revisit_and_comm_analytics.ipynb
> +    "def scale_data_units(value: float, bytes: bool = False) -> tuple[float, str]:\n",
Oh I see what you mean. Should I delete the MR I linked or leave that there? And should I make `revisit_and_comm_analytics` a folder with this notebook in it along with a `utils.py` file?

2025-01-02 22:46 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +  {
If you consider setting the plot theme to be part of the configuration, yes

2025-01-02 22:49 UTC, rtumin2 commented
> > @starskin I'll ask you to clean this up (e.g. by giving a better name to the map I made), but this change is needed to handle targets that exist as standalone targets and as a member of the target group. In this case, the agent id and target id are not the same.
> > [51e4364](https://github.com/sedaro/modsim-notebooks/commit/51e4364230d5a72f848169a854202139cf3c8256)
> 
> @rtumin2 I had originally tried to do something like this but the format of the revisit condition results is different between the two cases, so I decided to only use agent & target groups for the revisit condition. If a condition for a target is used instead of a target group, the following line in `target_revisit_results` breaks:
> 
> ```python
> for target_id, compliance_series in compliance_values.items():
> ```
> 
> Do you think it's a high priority to support both individual agents/targets in addition to agent/target groups?

I'm not suggesting you update the notebook to support single targets. The issue is that the original logic to determine the agent that corresponds to a specific target was not correct. Unless we want to restrict the user not to use an agent as a target when it is a part of the target group, we need to handle the agent id being different from the target id.

2025-01-02 22:50 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "def scale_data_units(value: float, bytes: bool = False) -> tuple[float, str]:\n",
see https://github.com/sedaro/modsim-notebooks/pull/46#discussion_r1898815164

2025-01-02 23:17 UTC, starskin commented on examples/revisit_and_comm_analytics.ipynb
> +    "- `REVISIT_ANALYSIS_CONDITION`: The name of the condition that is met when an observer agent revisits a target agent. There must be a `TargetGroupCondition` with this name on each of the observe
The `DATA_ANALYSIS_DATA_TYPES` variable also takes the names of the data types, not their IDs. I did it this way because the data type might have different IDs between different agent templates but in order for the data handling to work it has to have the same name, so that seems like the best way to specify the desired data types.

2025-01-03 19:56 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "DATA_ANALYSIS_DATA_TYPES: list[str] = []\n",
Oh I didn't realize that. Sick!

2025-01-03 19:57 UTC, rtumin2 commented on examples/revisit_and_comm_analytics.ipynb
> +    "- `REVISIT_ANALYSIS_CONDITION`: The name of the condition that is met when an observer agent revisits a target agent. There must be a `TargetGroupCondition` with this name on each of the observe
hmmm I had issues using the name but not the id. I can try again

2025-01-03 21:25 UTC, starskin commented
> I tested the revisit plots with this scenario and the plots look good! However I made a condition that is true only when multiple targets are available (count>0) and used that as the revisit condition. I'm not sure how to interpret this plot whenever two targets are involved. Maybe we should add a disclaimer that the results are really for conditions that use "ANY". Perhaps you have some insight into this?
> <img alt="image" width="1153" src="https://private-user-images.githubusercontent.com/27778749/399525978-14c875b9-da0d-4cc7-af72-9b3044540ae7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5Mzk4MDEsIm5iZiI6MTczNTkzOTUwMSwicGF0aCI6Ii8yNzc3ODc0OS8zOTk1MjU5NzgtMTRjODc1YjktZGEwZC00Y2M3LWFmNzItOWIzMDQ0NTQwYWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAzVDIxMjUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MDJhYjUyN2UwYmY5NjZiN2NlODVjNTBiZjI0MTQ0YmEwNjNjM2U3ZGU2MWIwMzg1M2QyYmNkYWFmOTYyNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9g4uNjLaQQALgra-lTw2nmGJeUstsiD1sHQ-EzQSZwA">
> 
> Also, here's the scenario I'm using to test [thanos-UnitedAirlinesAirTrafficControlScenariosimport.zip](https://github.com/user-attachments/files/18283717/thanos-UnitedAirlinesAirTrafficControlScenariosimport.zip)

This has been addressed [in this commit](https://github.com/sedaro/modsim-notebooks/pull/46/commits/d62401033b021819d73ccc949c5f4bb7a00fd25f).

2025-01-03 21:50 UTC, starskin commented
> I used this nb with TDRSS demo, and the data results say there is no transmit or receive data. However, web indicates that there was tx and rx.
> <img alt="image" width="641" src="https://private-user-images.githubusercontent.com/27778749/399534972-72941e56-aedc-4168-938f-c8db51428ef1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5Mzk4MDEsIm5iZiI6MTczNTkzOTUwMSwicGF0aCI6Ii8yNzc3ODc0OS8zOTk1MzQ5NzItNzI5NDFlNTYtYWVkYy00MTY4LTkzOGYtYzhkYjUxNDI4ZWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAzVDIxMjUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNTc0ODZmYWYyNmQwMzU2MTQ3MWIwODQzZjQxMTc2Nzg4NzRmMWQ0MWZkZDRiNmQwNGMwYzBlZGIyOTY4YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mpaSYXmxy_anP2bB4HP32D_MZ8TaNHrc8_fLCmvJgG0">
> 
> https://sedarocorp-my.sharepoint.us/:u:/g/personal/richard_tuminello_sedaro_com/EdLkZtDhDf9CqAEO4U4z16UB695istju8yjgMeUlcuoNfg?e=b57uLb

There appears to be two issues with your notebook that caused this:
- There is a data type ID instead of a data type name in the `DATA_ANALYSIS_DATA_TYPES` variable. It was looking for a data type with the name `N_eDZ9pUZ9eKAiAn0kxsF`, not finding anything like that, and correctly asserting that there was no data sent anywhere with this name. I've added a comment next to `DATA_ANALYSIS_DATA_TYPES` that tells users to use names so they will hopefully not accidentally use any IDs.
- The data analysis function needed to use your `observer_to_target_mapping`.
After fixing both of these issues the plots show the data transmission correctly.

2025-01-06 22:50 UTC, merged